language: python
python:
  - "3.5"
install:
  - pip install pandas
  - pip install xlrd
  - pip install openpyxl
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd SkillSet
  - python skill.py

notifications:
  email:
    recipients:
   #   - prithvisekhp@xxx.com #default sends to registered email
    on_success: always
    on_failure: always
